author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  url: http://inverseprobability.comtalkscam:
room: TBA
venue: Computer Laboratory, William Gates Building
postdir: ../../../mlatcl/mlphysical/_lectures/
slidedir: ../../../mlatcl/mlphysical/slides/
notedir: ../../../mlatcl/mlphysical/_notes/
notebookdir: ../../../mlatcl/mlphysical/_notebooks/
time:
