author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
venue: Virtual (Zoom)
postdir: ../../../mlatcl/mlphysical/_lectures/
slidedir: ../../../mlatcl/mlphysical/slides/
notedir: ../../../mlatcl/mlphysical/_notes/
notebookdir: ../../../mlatcl/mlphysical/_notebooks/
writediagramsdir: .
diagramsdir: ./slides/diagrams/
baseurl: "mlphysical/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.io/" # the base hostname & protocol for your site
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _mlphysical
transition: None
  
