author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
talkscam:
room: 
venue: Virtual (Zoom)
postdir: ../../../mlatcl/mlphysical/_lectures/
slidedir: ../../../mlatcl/mlphysical/slides/
notedir: ../../../mlatcl/mlphysical/_notes/
notebookdir: ../../../mlatcl/mlphysical/_notebooks/
transition: None
time:
