# Site settings
title: Neil Lawrence's Talks
email: N.Lawrence@sheffield.ac.uk
description: talks given by Neil Lawrence
baseurl: "/talks" # the subpath of your site, e.g. /blog/
reveal:
- width: 1024
- height: 768
youtube:
- width: 1024
- height: 768
talk_files: "http://inverseprobability.com/talks/slides/"
nbviewer: "http://nbviewer.ipython.org/"
basenb: "github/lawrennd/talks/blob/master/slides/" 
url: "http://inverseprobability.com" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd

analytics:
  google:
    tracking_id: UA-62968536-1

# Build settings
markdown: kramdown
