# Site settings
title: "Neil Lawrence's Talks"
email: N.Lawrence@sheffield.ac.uk
description: talks given by Neil Lawrence
baseurl: "/talks" # the subpath of your site, e.g. /blog/
reveal:
  width: 512
  height: 384
youtube:
  width: 512
  height: 384
talk_files: "http://inverseprobability.com/talks/slides/"
nbviewer: "http://nbviewer.ipython.org/"
basenb: "github/lawrennd/talks/blob/master/slides/" 
url: "http://inverseprobability.com" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd

comments: true
github:
  links: true
  fix: true

permalink: "/:categories/:title.html"

analytics:
  google:
    tracking_id: UA-62968536-1

# Build settings
markdown: kramdown
future: false
