# Site settings
title: "Neil Lawrence's Talks"
author: 
  name: Neil D. Lawrence
  email: 
description: talks given by Neil Lawrence
baseurl: "/talks" # the subpath of your site, e.g. /blog/

reveal:
  width: 512
  height: 384
youtube:
  width: 512
  height: 384

talk_files: "http://inverseprobability.com/slides/"

slides:
  url: https://inverseprobability.com
  dir: slides

notes:
  url: https://inverseprobability.com
  dir: notes

texdir: .
notes_files: "http://inverseprobability.com/talks/_notes/"
notesdir: _notes

url: "http://inverseprobability.com" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd
colab: https://colab.research.google.com
nbviewer: https://nbviewer.jupyter.org

comments: false
disqus:
  shortname: inverseprobabilitycom
ghub:
  edit: true
  repository: talks

permalink: "/:categories/:title.html"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/jekyll-theme
style: ndltalk

comments: True
disqus:
  shortname: inverseprobabilitycom

analytics:
  google:
    tracking_id: UA-62968536-1

# Build settings
markdown: kramdown
#future: true 
future: true
