# Site settings
title: "Neil Lawrence's Talks"
author: 
  name: Neil D. Lawrence
  email: 
description: talks given by Neil Lawrence
baseurl: "/talks" # the subpath of your site, e.g. /blog/
# Exclude directories for preprocessing.
exclude:
  - slides/reveal.js/plugin/markdown/example
#  - slides
#  - slides/reveal.js/css/theme/
reveal:
  width: 512
  height: 384
youtube:
  width: 512
  height: 384
talk_files: "http://inverseprobability.com/talks/slides/"
slidesdir: slides
notes_files: "http://inverseprobability.com/talks/_notes/"
notesdir: _notes
url: "http://inverseprobability.com" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd
colab: https://colab.research.google.com
nbviewer: https://nbviewer.jupyter.org

comments: true
disqus:
  shortname: inverseprobabilitycom
ghub:
  edit: true
  repository: talks

permalink: "/:categories/:title.html"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: ndltalk

analytics:
  google:
    tracking_id: UA-62968536-1

# Build settings
markdown: kramdown
#future: true #false
future: false
