layout: lecture
author:
- family: Lawrence
  given: Neil D.
  gscholar: r3SJcvoAAAAJ
  institute: Amazon Cambridge and University of Sheffield
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
ipynb: True
pdfnotes: True
postdir: ../../../mlatcl/mlss/_lectures/
slidedir: ../../../mlatcl/mlss/slides/
notedir: ../../../mlatcl/mlss/_notes/
notebookdir: ../../../mlatcl/mlss/_notebooks/
venue: MLSS, Stellenbosch, South Africa
geometry: ["a4paper", "margin=2cm"]
papersize: a4paper
