author:
- given: Neil D.
  family: Lawrence
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
url: http://inverseprobability.com
baseurl: /talks
diagramdir: slides/diagrams/
texdir: ../../neurips2014/
writediagramdir: .
ipynb: True
reveal: True
baseurl: "talks/" # the subpath of your site, e.g. /blog/
url: "https://inverseprobability.com/" # the base hostname & protocol for your site
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _neurips

