BASE=decision-making-and-diversity
MAKEFILESDIR=/Users/neil/lawrennd/lamd/lamd/makefiles
INCLUDESDIR=/Users/neil/lawrennd/lamd/lamd/includes
TEMPLATESDIR=/Users/neil/lawrennd/lamd/lamd/templates
SCRIPTDIR=/Users/neil/lawrennd/lamd/lamd/scripts
include $(MAKEFILESDIR)/make-talk-flags.mk
include $(MAKEFILESDIR)/make-talk.mk
